string Solution::intToRoman(int A) {
    int count;
    string s="";

    if(A>=1000)
    {
        count=A/1000;
        while(count>0)
        {
            s+='M';
            count--;
        }
        A%=1000;
    }
    if(A>=900)
    {
        count=A/900;
        while(count>0)
        {
            s+='C';
            s+='M';
            count--;
        }
        A%=900;
    }
    if(A>=500)
    {
        count=A/500;
        while(count>0)
        {
            s+='D';
            count--;
        }
        A%=500;
    }
    if(A>=400)
    {
        count=A/400;
        while(count>0)
        {
            s+='C' ;
            s+='D';
            count--;
        }
        A%=400;
    }
    if(A>=100)
    {
        count=A/100;
        while(count>0)
        {
            s+='C';
            count--;
        }
        A%=100;
    }
    if(A>=90)
    {
        count=A/90;
        while(count>0)
        {
            s+='X';
            s+='C';
            count--;
        }
        A%=90;
    }
    if(A>=50)
    {
        count=A/50;
        while(count>0)
        {
            s+='L';
            count--;
        }
        A%=50;
    }
    if(A>=40)
    {
        count=A/40;
        while(count>0)
        {
            s+='X';
            s+='L';
            count--;
        }
        A%=40;
    }
    if(A>=10)
    {
        count=A/10;
        while(count>0)
        {
            s+='X';
            count--;
        }
        A%=10;
    }
    if(A>=9)
    {
        count=A/9;
        while(count>0)
        {
            s+='I';
            s+='X';
            count--;
        }
        A%=9;
    }
    if(A>=5)
    {
        count=A/5;
        while(count>0)
        {
            s+='V';
            count--;
        }
        A%=5;
    }
    if(A>=4)
    {
        count=A/4;
        while(count>0)
        {
            s+='I';
            s+='V';
            count--;
        }
        A%=4;
    }
    if(A>=1)
    {
        count=A/1;
        while(count>0)
        {
            s+='I';
            count--;
        }
        A%=1;
    }

    return s;
    
}
